version: 0.2
 
env:
  variables:
    AWS_REGION: "ap-south-2"
    ECR_REPO:
     "991524241826.dkr.ecr.ap-south-2.amazonaws.com/course-prarthana"
 
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION |
          docker login --username AWS --password-stdin
            991524241826.dkr.ecr.$AWS_REGION.amazonaws.com
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE
         _VERSION:0:7}
  build:
    commands:
      - cd day2-microservices/student-service
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
  post_build:
    commands:
      - docker push $ECR_REPO:$IMAGE_TAG
      - printf '[{"name":"student-service",
          "imageUri":"%s"}]' \
          $ECR_REPO:$IMAGE_TAG > imagedefinitions.json
 
artifacts:
  files: imagedefinitions.json

